### ISSUE TITLE
Add the remaining Julia language creator(s)

### ISSUE THREAD

**Issue by ararslan** [rekihattori/awesome-programmers#17]
The Julia language was created by Jeff Bezanson, Stefan Karpinski, and Viral Shah (as well as Jeff's PhD advisor, Alan Edelman). However, only Jeff and Stefan are present in the list. I think Viral should certainly also be included, and perhaps Alan as well.

**Comment by salman-bhai** [comment]
Go ahead and add him. Send a PR, referencing this Issue.
